version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: miketud/realestateapp-backend:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/realestate
      NODE_ENV: production

  frontend:
    image: miketud/realestateapp-frontend:latest
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
